# Generated by Django 5.1.7 on 2025-03-17 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_pelicula_reseña'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reseña',
            new_name='Resena',
        ),
    ]
