# Generated by Django 5.1.7 on 2025-03-17 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_reseña_resena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='fecha_estreno',
            field=models.IntegerField(),
        ),
    ]
